services:
  - type: web
    name: startgg-manager-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: startgg-manager-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: startgg-manager-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: startgg-manager-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: startgg-manager-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: startgg-manager-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database

databases:
  - name: startgg-manager-db
    databaseName: startgg_manager
    plan: free

